name: React Deployment
on:
  push:
    branches:
      - pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn Install
      run: |
        yarn install
    - name: Staging Build
      run: |
        yarn build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: workersdeck-fe
        AWS_ACCESS_KEY_ID: AKIA6NP4DNY6OJ7DMB4D
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: us-east-2
        SOURCE_DIR: "build"