name: s3-deployment-frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Build App
      run: |
       yarn && yarn build && ls *
      env:
        CI: "" 
    - name: Copy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: workersdeck-fe
        AWS_ACCESS_KEY_ID: AKIA6NP4DNY6OJ7DMB4D
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: us-east-2
        SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
